stages:
  train:
    cmd: python src/experiments/run_experiment.py
    deps:
      - src/experiments/run_experiment.py
      - dataset/DFDC
    outs:
      - models/meso4.weights.h5
  evaluate:
    cmd: python src/evaluate/evaluate_model.py
    deps:
      - models/meso.weights.h5
      - src/evaluate/evaluate_model.py
    metrics:
      - results/evaluate/metrics.json
