data:
  DATA_DIR_MESO: "dataset/openfaceforensic"
  DATA_DIR_EFFICIENT: "dataset/ef_openfaceforensic"
  IMAGE_SIZE: [256, 256]
  INPUT_SHAPE: [256, 256, 3]
  CLASSES: ['real', 'fake']

train:
  EPOCHS: 10
  BATCH_SIZE: 16

model:
  MODEL_MESO4_WEIGHT: "models/meso4/meso4.weights.h5"
  MODEL_MESO4_FULL: "models/meso4/meso4_full_model.h5"
  MODEL_EFFICIENTNET_FULL: "models/efficientnet/efficientnet_model.h5"
  MODEL_EFFICIENTNET_WEIGHT: "models/efficientnet/efficientnet_model.weights.h5"

output:
  RESULT_DIR: "results"
  RESULT_CONFUSION_MATRIX: "results/confusion_matrix.png"
  MODELS_PATH: "models"
  OUTPUT_DIR_MESONET: "results/mlflow_logs/mesonet/"
  OUTPUT_DIR_EFFICIENT: "results/mlflow_logs/efficientnet/"
  
mlflow:
  EXPERIMENT_NAME_MESO: "Deepfake detection_mesonet"
  EXPERIMENT_NAME_EFFICIENTNET: "Deepfake detection_efficientnet"
  MESO4_RUN_NAME: "Meso4_Run"
  EFFICIENTNET_RUN_NAME: "efficientnet_v1"
  MESO4_MODEL_NAME: "Meso4_Model"
  EFFICIENTNET_MODEL_NAME: "EfficientNet_Model"

parameters:
  OPTIMIZER: "adam"
  LOSS_FUNC: "binary_crossentropy"