data:
  REAL_DIR: "dataset/DFDC/real_small/"
  FAKE_DIR: "dataset/DFDC/fake_small/"
  IMAGE_SIZE: [256, 256]

train:
  EPOCHS: 10
  BATCH_SIZE: 20

model:
  PRETRAINED_WEIGHTS: "models/Meso4_DF.h5"

output:
  RESULT_DIR: "results"
  MODEL_WEIGHT_PATH: "models/meso4.weights.h5"
  MODEL_FULL_PATH: "models/meso4_full_model.h5"
  MODEL_OPT_FULL_PATH: "models/meso4_opt_full_model.h5"
  RESULT_CONFUSION_MATRIX: "results/confusion_matrix.png"
  MODELS_PATH: "models"
  

mlflow:
  EXPERIMENT_NAME: "Deepfake detection"