data:
  REAL_DIR: "dataset/DFDC/real_small/"
  FAKE_DIR: "dataset/DFDC/fake_small/"
  IMAGE_SIZE: [256, 256]

train:
  EPOCHS: 10
  BATCH_SIZE: 16

model:
  CUSTOM_WEIGHTS: "models/meso4.weights.h5"
  PRETRAINED_WEIGHTS: "models/Meso4_DF.h5"

output:
  RESULT_DIR: "results"
  MODEL_SAVE_PATH: "models/meso4.weights.h5"
  RESULT_CONFUSION_MATRIX: "results/confusion_matrix.png"