data:
  FAKE_DIR: "dataset/fake_and_real/fake/"
  REAL_DIR: "dataset/fake_and_real/real/"
  DATA_DIR: "dataset/fake_and_real"
  IMAGE_SIZE: [256, 256]

train:
  EPOCHS: 10
  BATCH_SIZE: 20

model:
  PRETRAINED_WEIGHTS: "models/Meso4_DF.h5"

output:
  RESULT_DIR: "results"
  MODEL_WEIGHT_PATH: "models/meso4.weights.h5"
  MODEL_FULL_PATH: "models/meso4_full_model.h5"
  MODEL_OPT_FULL_PATH: "models/meso4_opt_full_model.h5"
  RESULT_CONFUSION_MATRIX: "results/confusion_matrix.png"
  MODELS_PATH: "models"
  OUTPUT_DIR_MESONET: "results/mlflow_logs/mesonet/"
  OUTPUT_DIR_EFFICIENT: "results/mlflow_logs/efficientnet/"
  

mlflow:
  EXPERIMENT_NAME: "Deepfake detection"