name: Deploy Python App to Azure Web App - deepfake

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_609E9E02AF9A47B08E8F558EA3C8A8C4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0C3704FDE08942F2AC3F1744CBEF235D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8F6DD1092F7742CDB213BFF1A77A5C26 }}
          client-secret: ${{secrets.AZUREAPPSERVICE_CLIENTSECRET}}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'deepfake'
          slot-name: 'Production'
          package: .



