name: Deploy Streamlit App to Azure Web App - deepfake

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Verify Streamlit installation
        run: |
          streamlit --version

      - name: Verify required files exist
        run: |
          if [ ! -f "app.py" ]; then
            echo "Error: app.py not found"
            exit 1
          fi
          if [ ! -d "models" ]; then
            echo "Error: models directory not found"
            exit 1
          fi
          if [ ! -f "models/efficientnet/efficient_model.h5" ]; then
            echo "Error: EfficientNet model file not found"
            exit 1
          fi
          if [ ! -f "models/meso4/meso4_full_model.h5" ]; then
            echo "Error: MesoNet model file not found"
            exit 1
          fi
          if [ ! -f "frontend/images/artificial-intelligence.png" ]; then
            echo "Error: UI image file not found"
            exit 1
          fi
          echo "All required files verified successfully"
          
      - name: Create startup command file
        run: |
          echo "streamlit run app.py --server.port 8000 --server.address 0.0.0.0" > startup.sh
          chmod +x startup.sh
      
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            app.py
            requirements.txt
            models/**
            frontend/images/artificial-intelligence.png
            startup.sh
            !models/**/__pycache__/
            !models/**/*.pyc

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      contents: read
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'deepfake'
          slot-name: 'Production'
          startup-command: 'sh startup.sh'
        timeout-minutes: 30
        
      - name: Azure logout
        run: |
          az logout
        if: always()
